spring:
  application:
    name: social-media-test
  datasource:
    url: jdbc:mysql://localhost:3306/esun_social_media?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: esun_dbUser1
    password: dbUser_passw0rd1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
  # 啟用https
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myapp